// Plumber Bro interactive prototype. No customer data is transmitted or persisted.
const services=[
 ['Emergency Plumbing','Fast help for burst pipes, unexpected leaks and urgent plumbing problems.','emergency-plumbing'],
 ['Drain Cleaning','Get sinks, showers and drains flowing freely again.','drain-cleaning'],
 ['Leak Detection & Repair','Find the source of hidden leaks and put the right repair in place.','leak-detection'],
 ['Water Heater Services','Help with hot-water systems, repairs and replacement options.','water-heater'],
 ['Pipe Repair & Replacement','Repair damaged pipework and replace worn or corroded pipes.','pipe-replacement'],
 ['Sewer & Drain Services','Investigate blockages and drainage problems with specialist equipment.','sewer-inspection'],
 ['Toilet Repair & Installation','Sort running, leaking or blocked toilets, or fit a new one.','toilet-installation'],
 ['Tap & Fixture Installation','A fresh finish for taps, sinks, shower fittings and fixtures.','tap-installation']
];
const reviews=[['A leak, a clear explanation, a tidy finish.','“The plumber explained the repair clearly and left the kitchen clean and tidy. Exactly the sort of help you want when a pipe starts leaking.”','Leak repair'],['Straightforward from start to finish.','“It was easy to explain the problem, understand the options and arrange the next step. A refreshingly straightforward experience.”','General plumbing'],['Back to a bathroom that works.','“Our troublesome tap and running toilet were finally sorted. The difference to our everyday routine was immediate.”','Bathroom repairs']];
const faqs=[['Do you offer same-day plumbing service?','Call +44 20 7435 9719 to check the next available visit. Same-day appointments depend on your location, the job and the team’s availability.'],['Are your plumbers licensed and insured?','Please ask the team to confirm the qualifications and insurance relevant to your job. For gas-related work, request the attending engineer’s Gas Safe registration details before work begins.'],['What types of plumbing services do you provide?','Explore emergency plumbing, drain cleaning, leak detection, water heater services, pipe repairs, sewer and drain services, toilet repairs, and tap installation. Call to discuss your specific job.'],['Do you provide upfront pricing?','Ask for a clear quote before agreeing to work. The team can confirm call-out charges, parts, labour and any additional costs for your particular job.'],['How can I schedule a service?','Call +44 20 7435 9719. You can also explore the Request Service form in this prototype; demo submissions do not create a booking.']];
const map='https://www.google.com/maps/search/?api=1&query=London%2C%20Greater%20London';
const google='https://www.google.com/search?q=Plumber+Bro+London+reviews';
const cards=()=>services.map((s,i)=>`<a class="service-card" href="${s[2]}.html"><div class="service-image"><img src="assets/${s[2]}.png" alt="${s[0]} in a London home" loading="lazy"><span>0${i+1}</span></div><div class="service-copy"><h3>${s[0]}</h3><p>${s[1]}</p><span class="learn">Explore service <b>↗</b></span></div></a>`).join('');
document.querySelector('#remaining').innerHTML=`
<section id="services" class="section services"><div class="section-heading"><div><p class="eyebrow"><span class="tiny-line"></span> OUR SERVICES</p><h2>Expert help.<br>For every pipe, tap & drain.</h2></div><button class="btn outline request">Request Service <span>↗</span></button></div><div class="service-grid">${cards()}</div></section>
<section class="emergency"><div class="emergency-circle" aria-hidden="true">24/7</div><div><p class="eyebrow">HERE WHEN YOU NEED US</p><h2>Plumbing emergency?<br>We’re ready to help.</h2><a class="btn gold" href="tel:+442074359719">Call +44 20 7435 9719 <span>↗</span></a></div><p>A burst pipe doesn’t<br>wait until Monday.<br><strong>Neither should you.</strong></p></section>
<section class="section reviews" id="reviews"><div class="centre"><p class="eyebrow">CUSTOMER REVIEWS</p><h2>See why homeowners<br>choose us.</h2><p class="muted">Sample reviews for this design preview — not verified customer feedback.</p></div><div class="review-grid">${reviews.map((r,i)=>`<button class="review-card" data-review="${i}"><span class="quote-mark">“</span><h3>${r[0]}</h3><p>${r[1]}</p><div class="review-bottom"><span class="review-avatar">0${i+1}</span><span>${r[2]}<small>Illustrative review</small></span><span class="expand-icon" aria-label="Expand review">↗</span></div></button>`).join('')}</div><div class="centre"><a href="${google}" target="_blank" rel="noopener" class="btn outline">Find reviews on Google ↗</a><p class="small muted">Google search link · Business review profile to be connected</p></div></section>
<section class="section why" id="about"><div class="section-heading"><div><p class="eyebrow"><span class="tiny-line"></span> WHY CHOOSE US</p><h2>A better plumbing service.<br>From start to finish.</h2></div><p>Skilled work. Straight answers.<br>A little more care for the place you call home.</p></div><div class="why-grid">${[['Clear Communication','Know what’s happening, what your options are and what comes next.'],['Quality Workmanship','Thoughtful repairs and careful installation, with attention to the details.'],['Respect for Your Home','Care for your space, protection for surfaces and a tidy finish.'],['Customer-First Service','Practical solutions built around your home and your plumbing needs.']].map((x,i)=>`<article><span class="number">0${i+1}</span><div><h3>${x[0]}</h3><p>${x[1]}</p></div></article>`).join('')}</div></section>
<section class="section areas" id="areas"><div><p class="eyebrow"><span class="tiny-line"></span> CLOSE TO HOME</p><h2>Proudly serving<br>London &<br>Greater London.</h2><p>From a dripping tap to an urgent repair,<br>call to check availability in your area.</p><button class="btn call request">Request Service ↗</button></div><div class="map-wrap"><iframe title="Map of London and Greater London" loading="lazy" referrerpolicy="no-referrer-when-downgrade" src="https://maps.google.com/maps?q=London%2C%20Greater%20London&t=&z=10&ie=UTF8&iwloc=&output=embed"></iframe><a href="${map}" target="_blank" rel="noopener" class="map-caption"><span>London, Greater London</span><strong>Open Google Maps ↗</strong></a><div class="area-tags"><span>Central London</span><span>North London</span><span>South London</span><span>East London</span><span>West London</span></div></div></section>
<section class="section faq" id="faq"><div><p class="eyebrow"><span class="tiny-line"></span> A LITTLE CLARITY</p><h2>FAQ</h2><p>Quick answers before<br>you arrange a visit.</p></div><div class="faq-list">${faqs.map((f,i)=>`<button data-faq="${i}"><span>${f[0]}</span><b>+</b></button>`).join('')}</div></section>
<section class="final-cta"><div><p class="eyebrow">LET’S GET IT SORTED</p><h2>Good plumbing.<br>One call away.</h2><a class="btn gold" href="tel:+442074359719">Call +44 20 7435 9719 ↗</a></div></section>
<footer><div class="footer-grid"><div><a class="brand" href="index.html"><span class="brandmark">p<span>•</span></span>Plumber Bro.</a><p>At your service, 24/7.</p><a class="contact-line" href="tel:+442074359719">+44 20 7435 9719</a><a class="contact-line" href="${map}" target="_blank" rel="noopener">London, Greater London (Greater London) ↗</a><div class="socials" aria-label="Demo social links">${[['X','https://x.com'],['Instagram','https://instagram.com'],['Facebook','https://facebook.com'],['TikTok','https://tiktok.com'],['YouTube','https://youtube.com']].map(s=>`<a href="${s[1]}" target="_blank" rel="noopener" aria-label="${s[0]} — placeholder link">${s[0]}</a>`).join('')}</div><p class="small muted">Social links are placeholders.</p></div><div><h3>Explore</h3><a href="index.html">Home</a><a href="about.html">About</a><a href="services.html">Services</a><a href="${google}" target="_blank" rel="noopener" title="Placeholder Google reviews search">Reviews ↗</a><a href="index.html#faq">FAQ</a><button class="request">Contact</button></div><div><h3>Our services</h3>${services.map((s,i)=>`<a href="${s[2]}.html">${s[0]}</a>`).join('')}</div></div><div class="footer-base"><span>© ${new Date().getFullYear()} Plumber Bro. Design prototype.</span><span>Demo enquiries are not sent or stored.</span></div><div class="footer-wordmark" aria-hidden="true">Plumber Bro.</div></footer>
<button class="chat-launch" aria-label="Open AI demo chat"><span>✦</span> AI <span class="chat-label">Ask Plumber Bro</span></button>
<aside class="chat-box" aria-label="Plumber Bro demo chat" hidden><div class="chat-head"><div><strong>✦ Plumber Bro assistant</strong><small>Demo chat · No live agent</small></div><button class="close-chat" aria-label="Close chat">×</button></div><div id="chat-content"><h3>Let’s get acquainted.</h3><p>Enter your details to try the chat. This demo does not send or save them.</p><form id="chat-intake"><label>Name<input name="name" autocomplete="name" required maxlength="80" placeholder="Your name"></label><label>Mobile number<input name="phone" type="tel" autocomplete="tel" pattern="[+0-9 ()-]{7,20}" required placeholder="Your mobile number"></label><label>Address<textarea name="address" autocomplete="street-address" required maxlength="300" rows="2" placeholder="Your address"></textarea></label><button class="btn gold" type="submit">Start demo chat ↗</button></form></div></aside>
<dialog id="modal" aria-label="Plumber Bro details"><button class="modal-close" aria-label="Close dialog">×</button><div id="modal-content"></div></dialog>`;
const modal=document.querySelector('#modal'),content=document.querySelector('#modal-content');
function show(html){content.innerHTML=html;modal.showModal();document.body.classList.add('modal-open')}
function close(){modal.close();document.body.classList.remove('modal-open')}
modal.addEventListener('close',()=>document.body.classList.remove('modal-open'));
document.querySelector('.modal-close').onclick=close;
modal.addEventListener('click',e=>{if(e.target===modal){const r=modal.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)close()}});
const requestForm=()=>`<p class="eyebrow">REQUEST SERVICE</p><h2>What needs sorting?</h2><p>This is a demo form. For a real appointment, call <a href="tel:+442074359719">+44 20 7435 9719</a>.</p><form id="request-form"><div class="form-grid"><label>Name<input name="name" autocomplete="name" required maxlength="80"></label><label>Phone number<input name="phone" type="tel" autocomplete="tel" pattern="[+0-9 ()-]{7,20}" required></label></div><label>Service<select name="service">${services.map(s=>`<option>${s[0]}</option>`).join('')}</select></label><label>Tell us about the job<textarea name="message" rows="3" required maxlength="1500"></textarea></label><p class="small muted">Prototype only. Your details are not transmitted or saved.</p><button class="btn call" type="submit">Try demo request ↗</button></form>`;
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;
 if(b.matches('.request'))show(requestForm());
 if(b.dataset.review!==undefined){const r=reviews[+b.dataset.review];show(`<p class="eyebrow">ILLUSTRATIVE REVIEW · DESIGN PREVIEW</p><span class="quote-mark">“</span><h2>${r[0]}</h2><p class="large-quote">${r[1]}</p><p>${r[2]} · Sample content, not a verified testimonial</p><a class="btn outline" href="${google}" target="_blank" rel="noopener">Search Google reviews ↗</a>`)}
 if(b.dataset.faq!==undefined){const f=faqs[+b.dataset.faq];show(`<p class="eyebrow">FAQ</p><h2>${f[0]}</h2><p class="answer">${f[1]}</p><a class="btn call" href="tel:+442074359719">Speak to Plumber Bro ↗</a>`)}
});
document.addEventListener('submit',e=>{if(e.target.id==='request-form'){e.preventDefault();content.innerHTML=`<p class="eyebrow">DEMO COMPLETE</p><h2>That’s how a request works.</h2><p>No enquiry has been sent and no appointment has been booked. To arrange a real visit, call the team.</p><a class="btn gold" href="tel:+442074359719">Call +44 20 7435 9719 ↗</a>`}});
const chat=document.querySelector('.chat-box'),launcher=document.querySelector('.chat-launch');
launcher.onclick=()=>{chat.hidden=!chat.hidden;launcher.setAttribute('aria-expanded',String(!chat.hidden));if(!chat.hidden)chat.querySelector('input,button')?.focus()};
document.querySelector('.close-chat').onclick=()=>{chat.hidden=true;launcher.setAttribute('aria-expanded','false');launcher.focus()};
launcher.setAttribute('aria-expanded','false');
document.querySelector('#chat-intake').onsubmit=e=>{e.preventDefault();const name=new FormData(e.target).get('name').trim();document.querySelector('#chat-content').innerHTML=`<div id="messages" role="log" aria-live="polite"></div><form id="chat-send"><label class="sr-only" for="chat-message">Message</label><input id="chat-message" placeholder="Describe your plumbing issue…" required maxlength="700"><button aria-label="Send message" type="submit">↑</button></form><p class="small muted">Scripted demo · No messages sent or bookings made</p>`;addMessage(`Hi ${name || 'there'}! What can we help with? This is a scripted preview, so please call for real assistance.`,'bot');document.querySelector('#chat-send').onsubmit=ev=>{ev.preventDefault();const input=document.querySelector('#chat-message'),msg=input.value.trim();if(!msg)return;addMessage(msg,'user');input.value='';let reply='We can help you explore plumbing services in London and Greater London. Call +44 20 7435 9719 to confirm the right service and availability. This demo cannot book visits.';if(/leak|burst|flood|emergen/i.test(msg))reply='For an urgent leak or plumbing emergency, call +44 20 7435 9719 now. This demo cannot dispatch a plumber or assess an emergency.';else if(/price|cost|quote|charge/i.test(msg))reply='Prices depend on the work, parts and timing. Call +44 20 7435 9719 for a quote and to confirm any call-out charge before agreeing to work.';else if(/book|appoint|visit|today/i.test(msg))reply='To arrange a visit, call +44 20 7435 9719. The team can confirm available appointments. No booking is made through this demo.';else if(/toilet|tap|drain|pipe|water heater/i.test(msg))reply='You can explore that service in the service cards, then call +44 20 7435 9719 to discuss the problem and next available appointment.';addMessage(reply,'bot')};document.querySelector('#chat-message').focus()};
function addMessage(text,who){const p=document.createElement('p');p.className='message '+who;p.textContent=text;document.querySelector('#messages').append(p);p.scrollIntoView({block:'nearest'})}

