const page=document.body.dataset.page;
const details=[
 {intro:'When a pipe bursts or a leak cannot wait, the first step is to explain what is happening and check the earliest available visit.',items:['Investigation of sudden leaks and burst pipework','Assessment of overflowing plumbing fixtures','Repair options for damaged fittings and connections','Advice on follow-up work once the immediate problem is assessed'],factors:'Urgency, time of attendance, access to the damaged pipework and the parts required.',prepare:'Tell us when the problem started, where the water is appearing and whether it is still getting worse.'},
 {intro:'Slow sinks, standing shower water and recurring blockages need an approach that matches the cause, rather than a temporary fix.',items:['Investigation of slow-draining sinks, baths and showers','Assessment of blocked waste pipes and traps','Suitable drain-clearing options for the affected pipework','Discussion of recurring blockages and further inspection if needed'],factors:'The location and severity of the blockage, pipe access and the clearing equipment needed.',prepare:'Tell us which fixtures are affected, how long they have been draining slowly and whether the blockage keeps returning.'},
 {intro:'A damp patch or an unexplained drip can come from more than one source. Start with a careful assessment before agreeing to a repair.',items:['Assessment of visible leaks and suspected hidden pipe leaks','Inspection of accessible pipework, valves and fittings','Discussion of detection methods and access requirements','A repair proposal and any follow-up work identified'],factors:'The location of the suspected leak, diagnostic work, access requirements and the extent of the repair.',prepare:'Describe any damp patches, visible dripping or recent changes. Mention whether the issue affects hot water, cold water or both.'},
 {intro:'Hot-water problems can affect the whole household. Describe your system and its symptoms so the team can discuss an appropriate inspection.',items:['Assessment of inconsistent or absent hot water','Inspection of accessible water connections and cylinder pipework','Discussion of repair or replacement options','Confirmation of the specialist qualifications required for the work'],factors:'The type and size of the hot-water system, its condition, replacement parts and any specialist work needed.',prepare:'Include the system make and model if known, its approximate age and the symptoms. Gas or electrical work must be confirmed with an appropriately qualified professional.'},
 {intro:'Damaged, worn or leaking pipework needs a repair suited to its material, location and condition.',items:['Assessment of leaking or damaged water pipes','Replacement options for worn sections and fittings','Discussion of materials and access to the pipework','Checks of the repaired section and next steps for any wider issues'],factors:'Pipe material, the length of the affected section, access, fittings and any necessary making-good work.',prepare:'Explain where the pipe is located and whether it is exposed, under a floor or behind a wall. Mention any known previous repairs.'},
 {intro:'Recurring drainage trouble may need a closer look at the line itself. Discuss the symptoms and access points before arranging an inspection.',items:['Assessment of recurring drain blockages and backups','Discussion of camera inspection where appropriate','Identification of suitable clearing or repair options','Clear explanation of findings and proposed next steps'],factors:'Drain access, the length and condition of the line, inspection equipment and the extent of clearing or repair.',prepare:'Tell us whether one fixture or several are affected, where the drain access is and whether you have previous inspection findings.'},
 {intro:'From a cistern that keeps running to a new toilet installation, discuss the right solution for your bathroom and existing connections.',items:['Assessment of running cisterns and leaking toilet fittings','Discussion of flushing and filling mechanism repairs','Replacement toilet fitting options','Connection, access and disposal requirements for a new installation'],factors:'The fault, replacement components, the chosen toilet, existing connections and any removal or disposal work.',prepare:'Tell us whether you need a repair or a new installation, and whether you have already purchased the toilet or replacement parts.'},
 {intro:'A well-fitted tap or fixture makes everyday use easier. Check compatibility and access before arranging the installation.',items:['Replacement of suitable kitchen and bathroom taps','Assessment of dripping fixtures and worn connections','Discussion of sink, shower fitting and valve installation','Checks of fitting compatibility and accessible supply connections'],factors:'The fixture type, compatibility, access beneath the fitting, connection changes and whether you supply the new fixture.',prepare:'Tell us what you want fitted, where it will go and whether you already have the fixture. Include a model name if available.'}
];
// Retain the shared footer, dialogs and chat while replacing homepage sections.
document.querySelectorAll('#remaining > section').forEach(section=>section.remove());
const quoteForm=(service)=>`<aside class="quotation" id="quotation"><p class="eyebrow">LET’S ARRANGE THE NEXT STEP</p><h2>Request a quote.</h2><p>Leave your details for a representative to discuss your ${service.toLowerCase()} enquiry.</p><div class="demo-notice">Demo form: details are not sent or saved. No callback is arranged. For a real enquiry, <a href="tel:+442074359719">call +44 20 7435 9719</a>.</div><form class="quote-form"><input type="hidden" name="service" value="${service}"><label for="customer-name">Your name<input id="customer-name" name="name" autocomplete="name" required maxlength="80" placeholder="Full name"></label><label for="customer-phone">Contact number<input id="customer-phone" name="phone" type="tel" inputmode="tel" autocomplete="tel" required minlength="7" maxlength="25" placeholder="Your mobile or phone number"></label><label for="customer-address">Property address<textarea id="customer-address" name="address" autocomplete="street-address" required maxlength="400" rows="3" placeholder="House number, street, town and postcode"></textarea></label><label for="customer-job">Tell us about the job <span class="muted">(optional)</span><textarea id="customer-job" name="job" maxlength="1500" rows="3" placeholder="Describe the issue and a suitable time to contact you"></textarea></label><p class="quote-service">Enquiry: <strong>${service}</strong></p><button class="btn gold" type="submit">Preview quote request ↗</button><p class="small muted">No price or appointment is confirmed by this form.</p><div class="quote-result" role="status" tabindex="-1" hidden></div></form></aside>`;
const breadcrumb=(name)=>`<nav class="breadcrumbs" aria-label="Breadcrumb"><a href="index.html">Home</a><span>/</span>${page==='about'||page==='services'?'':`<a href="services.html">Services</a><span>/</span>`}<span aria-current="page">${name}</span></nav>`;
let output='';
if(page==='about'){
 output=`${breadcrumb('About')}<section class="page-intro"><div><p class="eyebrow">ABOUT PLUMBER BRO</p><h1>Local help.<br>A little more care.</h1><p>Plumber Bro brings a straightforward approach to plumbing across London and Greater London. From small repairs to urgent problems, start with a conversation about what your home needs.</p><a class="btn gold" href="services.html">Explore our services ↗</a></div><img src="assets/hero.png" alt="Plumber working at a kitchen sink"></section><section class="page-section"><p class="eyebrow">HOW WE APPROACH YOUR HOME</p><h2>Clear at every step.</h2><div class="about-values">${[['Listen first','Describe the problem, your property and what you need help with.'],['Explain the options','Discuss the proposed work and ask for a quote before agreeing to proceed.'],['Respect your space','Careful access, clear communication and attention to your home.']].map((x,i)=>`<article><span class="number">0${i+1}</span><h3>${x[0]}</h3><p>${x[1]}</p></article>`).join('')}</div><div class="page-banner"><div><h2>London & Greater London.</h2><p>Call to check service availability in your area.</p></div><a class="btn call" href="tel:+442074359719">Call +44 20 7435 9719 ↗</a></div></section>`;
}else if(page==='services'){
 output=`${breadcrumb('Services')}<section class="page-section service-directory"><p class="eyebrow">OUR SERVICES</p><h1>Everyday repairs.<br>Expert attention.</h1><p class="directory-lead">Choose a service for detailed information, quote-based pricing and a contact form. Serving London and Greater London.</p><div class="service-grid">${cards()}</div><div class="page-banner"><div><h2>Not sure where to start?</h2><p>Tell us about the problem and discuss the right next step.</p></div><a class="btn call" href="tel:+442074359719">Call +44 20 7435 9719 ↗</a></div></section>`;
}else{
 const i=services.findIndex(s=>s[2]===page),s=services[i],d=details[i];
 output=`${breadcrumb(s[0])}<section class="page-intro"><div><p class="eyebrow">LONDON & GREATER LONDON</p><h1>${s[0]}</h1><p>${d.intro}</p><div class="hero-buttons"><a href="#quotation" class="btn gold">Request a quote ↗</a><a class="btn outline" href="tel:+442074359719">Call Now ↗</a></div></div><img src="assets/${s[2]}.png" alt="${s[0]} work"></section><section class="service-detail-layout"><div class="service-information"><section><p class="eyebrow">THE DETAILS</p><h2>How we can help.</h2><ul class="included-list">${d.items.map(x=>`<li>${x}</li>`).join('')}</ul></section><section class="pricing-panel"><p class="eyebrow">PRICING</p><h2>Quoted for your job.</h2><p>Request a quote for ${s[0].toLowerCase()}. A price can be discussed once the job has been assessed; some work may need a visit before a firm quote is possible.</p><h3>What affects the price?</h3><p>${d.factors}</p><h3>What to confirm in your quote</h3><p>Ask for labour, parts, any call-out or out-of-hours charges, VAT where applicable, and any exclusions to be clearly set out before you agree to work.</p><a href="#quotation" class="text-link">Request your quotation ↗</a></section><section><h2>Before you enquire.</h2><p>${d.prepare}</p><h3>What happens next?</h3><ol class="next-steps"><li>Share your name, contact number, address and job details.</li><li>A representative can review the enquiry and discuss scope and availability once the live enquiry service is connected.</li><li>Confirm the quote and any appointment directly with the team.</li></ol><p class="small muted">This prototype does not send enquiries. Please call for a real quotation.</p></section><a class="text-link" href="services.html">← Explore all services</a></div>${quoteForm(s[0])}</section>`;
}
document.querySelector('#page-content').innerHTML=output;
document.querySelectorAll('.nav nav a').forEach(a=>{if(a.getAttribute('href')===(page==='about'?'about.html':'services.html'))a.setAttribute('aria-current','page')});
document.querySelector('.quote-form')?.addEventListener('submit',e=>{e.preventDefault();const form=e.currentTarget;const name=form.elements.name,phone=form.elements.phone,address=form.elements.address;for(const field of [name,address]){field.setCustomValidity(field.value.trim()?'':'Please complete this field.')}phone.setCustomValidity((phone.value.match(/\d/g)||[]).length>=7?'':'Please enter a contact number with at least seven digits.');if(!form.reportValidity())return;const result=form.querySelector('.quote-result');result.textContent='Demo request previewed. Your details have not been sent or saved, and no callback has been arranged. Call +44 20 7435 9719 to request a real quotation.';result.hidden=false;result.focus();form.reset()});
document.querySelector('.quote-form')?.addEventListener('input',e=>{e.target.setCustomValidity?.('')});
